# -*- ruby -*-

APP        = "stack"
APP_TEST   = "test_stack"
SRCS       = %w{ ./my_stack.cpp ./main.cpp }
TEST_SRCS  = %w{ ./test_stack.cpp }
CXX        = "xcrun"
OSX_LIBS   = "-lgtest -lgtest_main"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
