# -*- ruby -*-

APP       = "cpp.tuple"
SRCS      = %W{ ./cpp.tuple.cpp }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = ""

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
