# -*- ruby -*-

SRCS     = %w{./random.plot.cpp}
APP      = "random.plot"
TEST_APP = "test.random.plot"
CXX      = "xcrun clang++"
CXXFLAGS = ":v :Os"

load '~/code/build/app2.rake'

task :default => [:osx]
