# -*- ruby -*-

SRC       = "move_if_noexcept"
SRCS      = %W{ ./#{SRC}.cpp }
APP       = "#{SRC}"
CXX       = "xcrun"
CXXFLAGS  = ":Os"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
