# -*- ruby -*-

SRC       = "test_zlib"
SRCS      = %W{ ./#{SRC}.cpp ./zlib.cpp }
APP       = "#{SRC}"
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = ":s z"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
