# -*- ruby -*-

SRC       = "test_gz"
SRCS      = %W{ ./#{SRC}.cpp ./gzip.cpp ./zlib.cpp}
APP       = "#{SRC}"
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = ":s z"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
