# -*- ruby -*-

SRCS      = %w{ forward.list.cpp }
TEST_SRCS = %w{ test_forward.list.cpp }
APP       = "forward.list"
CXX       = "xcrun"
CXXFLAGS  = ":d"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
