# -*- ruby -*-

SRCS      = %w{ ./functional.cpp }
TEST_SRCS = %w{ ./test_functional.cpp }
APP       = "functional"
CXX       = "xcrun"
#CXXFLAGS  = ":d"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
