# -*- ruby -*-

SRC       = "sender"
SRCS      = %W{ ./#{SRC}.cpp }
APP       = "#{SRC}"
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = ":s"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
