# -*- ruby -*-

APP       = "ssl"
APP_TEST  = "test_#{APP}"
SRCS      = %w{ main.cpp }
TEST_SRCS = %w{ ./cipher.cpp ./test_cipher.cpp
              }
INCS      = ""
CXX       = "c++11"          # c++0x, clang++, blank
CXXFLAGS  = ":v :d"          # :d , :O0 :O3 :w = -Wall
LIBS      = ":r :t :s :f ssl crypto"

load "~/code/build/app2.rake"

#task :default => [:test]
