#-*- ruby -*-   

require 'rake/clean'

task :default => [TARGET]

CLEAN.include("*.o")
CLOBBER.include(TARGET)

LDFLAGS  = ''
LIBS     = '-lruby -lobjc -ldl'
CXXFLAGS = '-I/usr/lib/ruby/1.8/universal-darwin11.0'
SRC      = FileList['*.cpp']
OBJ      = SRC.ext('o')

rule '.o' => '.cpp' do |t|
  sh "g++ -O3 -c -o #{t.name} #{t.source} #{CXXFLAGS}"
end

file TARGET => OBJ do
  sh "g++ -o #{TARGET} #{OBJ} #{LDFLAGS} #{LIBS}"
end
                
task :run => [TARGET] do
  sh "./#{TARGET}"
end

file 'embed.basic.o' => ['embed.basic.cpp']
