APP       = "driver"
APP_TEST  = "test_#{APP}"
SRCS      = %w{ driver.cpp http_client.cpp }
TEST_SRCS = %w{ test_http_client.cpp }
CXX       = "xcrun"         # c++0x, clang++, blank
CXXFLAGS  = ":v :d"         # :d , :O0 :O3 :w = -Wall
LIBS      = ":s :t"

load '~/code/build/app2.rake'
CLOBBER.include("*.o")

task :default => [:osx]
