# -*- ruby -*-

SRCS     = %w{ ./main.cpp }
APP      = "tp"
CXX      = "clang++"
INCS     = "~/develop/include"
CXXFLAGS = ":O3"
LIBS     = ":t :s"

load "~/code/build/app2.rake"

task :default => [:osx]
