# -*- ruby -*-
SRCS     = %w{main.cpp}
APP      = "thread_pool"
WIN_LIBS = "-lboost_thread-mt -lboost_system-mt"
OSX_LIBS = "-lboost_thread-mt -lboost_system-mt"

DIR = File.dirname __FILE__

load '~/code/build/app.rake'
