# -*- ruby -*-

APP       = "accumulate"
SRCS      = %W{ ./accumulate.cpp }
CXX       = "g++"
CXXFLAGS  = ":Os"
LIBS      = ""

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
