# -*- ruby -*-

APP       = "accumulate"
APP_TEST  = "test_#{APP}"
SRCS      = %W{ ./#{APP}.cpp }
TEST_SRCS = %W{ ./test_#{APP}.cpp }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = "gmock"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
