# -*- ruby -*-

SRCS     = %w{decompose.cpp}
APP      = "decompose"
CXX      = "xcrun"            # c++0x, clang++, blank
CXXFLAGS = ":v :d :w"         # :d , :w=-Wall :O0 :O3
LDFLAGS  = "/opt/homebrew/opt/icu4c/lib"
INCS     = "/opt/homebrew/opt/icu4c/include"
LIBS     = "icuuc icudata" 

load '~/code/build/app2.rake'
# CLOBBER.include("a.out")

 task :default => [:osx]
