# -*- ruby -*-

APP       = "mruby.test"
SRCS      = %W{ ./main.cpp }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
INCS      = ":mvm"
LIBS      = "mruby"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
