# -*- ruby -*-

APP       = "mandelbrot_tbb"
SRCS      = %W{ ./mandelbrot_tbb.cpp }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = "tbb tiff"
FRAMEWORKS = ""

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
