#-*- ruby -*-   

require 'rake/clean'

TARGET = 'http'

task :default => [:run]

CLEAN.include("*.o").include("Makefile").include("*.log")
CLOBBER.include(TARGET).include("*.bun*")

LIBS      = ""
CXXFLAGS  = "-I/usr/local/include"
SRC       = FileList["http_parser.cpp"]
OBJ       = SRC.ext('o')

rule '.o' => '.cpp' do |t|
  sh "clang++ -c -O3 -o #{t.name} #{t.source} #{CXXFLAGS}"
end

file TARGET => OBJ do
  sh "clang++ -o #{TARGET} #{OBJ}  #{LIBS}"
end

task :run => [TARGET] do
  sh "./#{TARGET}"
end
