# -*- ruby -*-

APP       = "pair_client"
SRCS      = %W{ ./pair_client.cpp }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = "zmq"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
