#-*- ruby -*-   

APP      = "jukebox"
SRCS     =  %w{ rubyeval.cpp jukebox.cpp jukebox_ext.cpp app.cpp main.cpp }
CXX      = "clang++"
CXXFLAGS = ":Os"
INCS     = ":rice"
LDFLAGS  = ":rice"
LIBS     = ":rice"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
