# -*- ruby -*-

APP       = "fold_left_comm"
SRCS      = %W{ ./fold_left_comma.cpp }

CXX       = "g++"
CXXFLAGS  = ":Os"
LIBS      = ""

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
