# -*- ruby -*-

APP       = "usbmux"
APP_TEST  = "test_#{APP}"
SRCS      = %w{ 
                ~/code/develop/src/ByteBuffer.cpp
                ./develop/src/usbmux.cpp
                ./main.cpp 
              }

TEST_SRCS = %w{ 
                ~/code/develop/src/ByteBuffer.cpp
                ./develop/src/usbmux.cpp
                ./test_main.cpp
              }

HOME      = ENV['HOME']
INCS      = "#{HOME}/code/app/usbmux/develop/include #{HOME}/code/develop/include"
CXX       = "clang++"         # c++0x, clang++, blank
CXXFLAGS  = ":v :O3"          # :d, :O0 :O3 :w = -Wall
LIBS      = ":s "

load "~/code/build/app2.rake"

# task :default => [:test]
