# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'minitest' do
  # with Minitest::Unit
  watch(%r|^lib/sky/([^/]+)\.rb|) { |m| 
    "test/test_#{m[1]}.rb" 
  }
  watch(%r|^lib/sky/([^/]+)\.rb|)  { |m| "test/test_#{m[1]}.rb" }
  watch(%r|^test/test_helper\.rb|) { "test" }
end
