# This file is part of the C++ dlopen mini HOWTO. You can find the complete
# HOWTO and/or updated versions at
# http://www.isotton.com/howtos/C++-dlopen-mini-HOWTO/
#
# Copyright 2002-2006 Aaron Isotton <aaron@isotton.com>
# Licensed under the GNU GPL.

example1: main.cpp hello.dylib
	$(CXX) $(CXXFLAGS) -o example1 main.cpp

hello.dylib: hello.cpp
	$(CXX) $(CXXFLAGS) -shared -o hello.dylib hello.cpp

clean:
	rm -f example1 hello.dylib

.PHONY: clean
