# -*- ruby -*-

APP       = "tf"
SRCS      = %W{ ./tf.cpp }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
INCS      = "/usr/local/include/tf /usr/local/include/eigen3"
LIBS      = "tensorflow_cc"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
