# -*- ruby -*-

APP       = "page"
SRCS      = %W{ ./page.cpp }
CXX       = "g++"
CXXFLAGS  = ":Os"
LIBS      = ":f :s"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
