# -*- ruby -*-

SRCS      = %w{ ./alias.cpp }
TEST_SRCS = %w{ ./test_alias.cpp }
APP       = "alias"
CXX       = "clang++"
CXXFLAGS  = ":Os"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
