# -*- ruby -*-

SRCS      = %w{ PTreeParser.cpp ~/develop/src/BPList.cpp ~/develop/src/BPListRepr.cpp 
                ~/develop/src/ByteBuffer.cpp ~/develop/src/Base64.cpp
                main.cpp
              }
TEST_SRCS = %w{ TestPtreeParser.cpp }
APP       = "main"
APP_TEST  = "test.main"
INCS      = "/Users/yielding/develop/include"
CXX       = "c++0x"        # c++0x, clang++, blank
CXXFLAGS  = ":debug"       # :debug, :nodebug
LIBS      = ":f :s"

load '~/code/build/app2.rake'
