# -*- ruby -*-

APP        = "black_scholes"
APP_TEST   = "test_#{APP}"
SRCS       = %W{ ./#{APP}.cpp }
TEST_SRCS  = %W{ ./test_#{APP}.cpp } + SRCS
CXX        = "xcrun"
CXXFLAGS   = ":Os"
FRAMEWORKS = "OpenCL"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
