# -*- ruby -*-

APP       = "accumulate"
APP_TEST  = "test_#{APP}"
SRCS      = %W{ ./#{APP}.cpp }
TEST_SRCS = %W{ ./test_numeric.cpp
                ./test_algorithm.cpp 
                ./test_map.cpp 
                ./test_set.cpp 
                ./test_vector.cpp 
                ./test_list.cpp 
                ./test_lambda.cpp 
                ./test_idiom.cpp 
              }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = "gmock"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
