group :test, :development do
  source 'https://rubygems.org'
  gem 'guard'
  gem 'guard-rspec'
  gem 'logger'
  gem 'ostruct'
  gem 'terminal-notifier-guard', '~> 1.7.0'
  gem 'terminal-notifier'
end
