# -*- ruby -*-

APP       = "develop_test"
APP_TEST  = "test_#{APP}"
SRCS      = %W{ ../src/byte_buffer2.cpp }
TEST_SRCS = %W{ ./test_byte_buffer2.cpp } + SRCS
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = ""

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

#task :defalut => [:run_test]
task :default => [:run_test] do; end
