# -*- ruby -*-

SRC       = "algo.sort.filter"
SRCS      = %W{ ./#{SRC}.cpp }
APP       = "#{SRC}"
CXX       = "g++"
CXXFLAGS  = ":Os"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
