# -*- ruby -*-

APP       = "avg"
APP_TEST  = "test_#{APP}"
SRCS      = %W{ ./avg.cpp }
TEST_SRCS = %W{ } + SRCS
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = ""

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
