# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'ch9'
  app.files_dependencies 'app/sample_for_group_table.rb' => 'app/sample_for_section_table.rb',
                         'app/sample_for_movable_row.rb' => 'app/sample_for_insertable_row.rb'

end
