#-*- ruby -*-   

require 'rake/clean'

TARGET = 'http'

task :default => [:run]

CLEAN.include("*.o").include("Makefile").include("*.log")
CLOBBER.include(TARGET).include("*.bun*")

LIBS      = ""
CXXFLAGS  = "-I/Users/yielding/opensource/boost-svn"
SRC       = FileList["http_parser.cpp"]
OBJ       = SRC.ext('o')

rule '.o' => '.cpp' do |t|
  #sh "g++-4.2 -c -O7 -DBOOST_VERSION=103900 -o #{t.name} #{t.source} #{CXXFLAGS}"
  sh "g++-4.2 -c -O7  -o #{t.name} #{t.source} #{CXXFLAGS}"
end

file TARGET => OBJ do
  sh "g++-4.2 -o #{TARGET} #{OBJ}  #{LIBS}"
end

task :run => [TARGET] do
  sh "./#{TARGET}"
end
