# -*- ruby -*-

APP       = "xll"
APP_TEST  = "test_#{APP}"
SRCS      = %w{ 
                ./bin_field.cpp
                ./char_field.cpp
                ./main.cpp 
              }

TEST_SRCS = %w{ 
                ./bin_field.cpp
                ./char_field.cpp
                ./main.cpp
              }

CXX       = "g++"          # c++0x, clang++, blank
CXXFLAGS  = ":v :O3"       # :d, :O0 :O3 :w = -Wall
LIBS      = ":f :s"

load "~/code/build/app2.rake"

task :default => [:test]
