# -*- ruby -*-
SRCS     = %w{pipe.cpp}
APP      = "pipe"
WIN_LIBS = "-lboost_thread-mt -lboost_system-mt"
OSX_LIBS = ""

DIR = File.dirname __FILE__

load '~/code/build/app.rake'
CLOBBER.include("hello").include("hello.tee")
