#-*- ruby -*-   

SRCS     = %w{ if_vim.cpp }
APP      = "if_vim2"
CXX      = "clang++"
CXXFLAGS = ":Os"
INCS     = ":rice"
LDFLAGS  = ":rice"
LIBS     = ":rice"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
