# -*- ruby -*-

APP       = "cpp.api2"
SRCS      = %W{ ./cpp.api2.cpp }
CXX       = "g++"
CXXFLAGS  = ":Os"
LIBS      = "sqlite3"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
