# -*- ruby -*-

APP       = "server"
SRCS      = %W{ ./server.cpp }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = "zmqpp zmq"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
