# -*- ruby -*-

SRC       ="avltree"
SRCS      = %W{ ./#{SRC}.cpp }
TEST_SRCS = %W{ ./test_#{SRC}.cpp }
APP       = "#{SRC}"

CXX       = "xcrun"           # xcrun(clang++ for Apple compiler), c++0x, clang++, blank
#CXX      = "c++11"           # xcrun(clang++ for Apple compiler), c++0x, clang++, blank
CXXFLAGS  = ":v :O3"          # :d, :O0 :O3 :w = -Wall
LIBS      = ":s :f"

load "~/code/build/app2.rake"

task :default => [:osx]
