local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("init_clang", {
    t({"cmake_minimum_required (VERSION "}), i(1, "3.30.0"), t({")","",
"set (CMAKE_CXX_STANDARD 26)",
"set (CMAKE_CXX_COMPILER clang++)",
"set (CMAKE_EXPORT_COMPILE_COMMANDS ON)",
"set (HOME $ENV{HOME})",
"",
"project ("}), i(2, "ProjectName"), t({")", "",
"set (SOURCES",
"\t"}), i(3, "$2.cpp"), t({"",
")",
"",
"find_package("}), i(4, "library"), t({")",
"",
"include_directories (",
"\t/usr/local/include",
"\t/opt/homebrew/include",
"\t${CMAKE_CURRENT_SOURCE_DIR}",
")",
"",
"link_directories (",
"\t${HOME}/.local/lib",
"\t/usr/local/lib",
"\t/opt/homebrew/lib",
")",
"",
"add_executable ("}), i(5, "$2"), t({"",
"\t${SOURCES}",
")",
"",
"target_link_libraries ("}), i(6, "$2"), t({"",
")",
""}),
  }),

  s("init_g++", {
    t({"cmake_minimum_required (VERSION "}), i(1, "3.30.0"), t({")","",
"set (CMAKE_CXX_STANDARD 26)",
"set (CMAKE_CXX_COMPILER g++-15)",
"set (CMAKE_EXPORT_COMPILE_COMMANDS ON)",
"",
"project ("}), i(2, "ProjectName"), t({")", "",
"set (SOURCES",
"\t"}), i(3, "$2.cpp"), t({"",
")",
"",
"include_directories (",
"\t/usr/local/include",
"\t/opt/homebrew/include",
"\t${CMAKE_CURRENT_SOURCE_DIR}",
")",
"",
"link_directories (",
"\t/usr/local/lib",
"\t/opt/homebrew/lib",
")",
"",
"add_executable ("}), i(4, "$2"), t({"",
"\t${SOURCES}",
")",
"",
"target_link_libraries ("}), i(5, "$2"), t({"",
")",
""}),
  }),

  s("init_simple", {
    t({"cmake_minimum_required (VERSION "}), i(1, "3.30.0"), t({")","",
"set (CMAKE_CXX_STANDARD 26)",
"set (CMAKE_CXX_COMPILER g++-14)",
"set (CMAKE_EXPORT_COMPILE_COMMANDS ON)",
"",
"project ("}), i(2, "ProjectName"), t({")", "",
"set (SOURCES",
"\t"}), i(3, "$2.cpp"), t({"",
")",
"",
"include_directories (",
"\t/usr/local/include",
"\t/opt/homebrew/include",
"\t${CMAKE_CURRENT_SOURCE_DIR}",
")",
"",
"link_directories (",
"\t/usr/local/lib",
"\t/opt/homebrew/lib",
")",
"",
"add_executable ("}), i(4, "$2"), t({"",
"\t${SOURCES}",
")",
""}),
  }),
}
