#-*- ruby -*-   

require 'rake/clean'

TARGET = 'main'

task :default => [TARGET]

CLEAN.include("*.o").include("data_model_wrap*")
CLOBBER.include(TARGET)

LDFLAGS  = '-L/opt/local/lib/mysql5/mysql'
LIBS     = '-lruby -lobjc -ldl -lmysqlclient -lmysqlpp'
CXXFLAGS = '-I/opt/local/lib/ruby/1.8/i686-darwin9.2.2 -I/opt/loal/include/mysql++'
SRC      = FileList['*.cpp']
SRC.exclude('stdafx.cpp')
OBJ      = SRC.ext('o')

rule '.o' => '.cpp' do |t|
  sh "g++ -O2 -c -o #{t.name} #{t.source} #{CXXFLAGS}"
end

file TARGET => OBJ do
  sh "g++ -o main #{OBJ} #{LDFLAGS} #{LIBS}"
end
                
file "data_model_wrapper.cpp" => "data_model.i" do |t|
  sh "swig -ruby -c++ -o #{t.name} data_model.i"
end                                
    
task :run => [TARGET] do
  sh "./#{TARGET}"
end

file 'main.o'       => ['main.cpp', 'data_model_wrapper.cpp']
file 'data_model.o' => ['data_model.cpp']
file "data_model_wrapper.o" => ["data_model_wrapper.cpp"]
