# -*- ruby -*-

APP       = "hfsplus"
APP_TEST  = "test_#{APP}"
SRCS      = %w{ main.cpp }
TEST_SRCS = %w{ ./hfs_header.cpp ./test_hfs_header.cpp
                ./hfs_volume.cpp ./test_hfs_volume.cpp
                ./hfs_file.cpp   ./test_hfs_file.cpp
                ./btree.cpp      ./test_btree.cpp

                develop/src/ByteBuffer.cpp ./test_byte_buffer.cpp 
              }
INCS      = "#{ENV['DEV']}/include #{ENV['DEV']}/vendor/include"
CXX       = "clang++"         # c++0x, clang++, blank
CXXFLAGS  = ":v :d"          # :d , :O0 :O3 :w = -Wall
LIBS      = ":r :t :s :f"

load "~/code/build/app2.rake"

#task :default => [:test]
