# -*- ruby -*-

APP       = "cpp.api3"
SRCS      = %W{ ./cpp.api3.cpp }
CXX       = "xcrun"
CXXFLAGS  = ":Os"
LIBS      = "gmock sqlite3"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
