# -*- ruby -*-

APP       = "partial_regex"
APP_TEST  = "test_#{APP}"
SRCS      = %w{driver.cpp partial_regex.cpp}
TEST_SRCS = %w{partial_regex.cpp test_partial_regex.cpp}
CXX       = "c++0x"           # c++0x, clang++, blank
CXXFLAGS  = ":v"           # :d , :O0 :O3 :w = -Wall
LIBS      = ":r"

load '~/code/build/app2.rake'
