# -*- ruby -*-

SRCS      = %w{rexpr.cpp}
TEST_SRCS = %w{test_rexpr.cpp}
APP       = "rexpr"
APP_TEST  = "test_rexpr"
CXX       = "xcrun"    # c++0x, clang++, blank
CXXFLAGS  = ":v :O3"       
LIBS      = ":t :s" 
INCS      = "/Users/yielding/opensource/spirit/include"

load '~/code/build/app2.rake'
CLOBBER.include("*.o")
