# -*- ruby -*-

APP       = "md_analyzer"
SRCS      = %w{ ./data_store.cpp 
                ./data_store_ext.cpp 
                ./file_system.cpp 
                ./file_system_ext.cpp 
                ./file.cpp
                ./file_ext.cpp
                ./main.cpp
              }

TEST_SRCS = %w{ ./test_main.cpp 
              }

INCS      = ":mvm"
CXX       = "clang++"          # c++0x, clang++, blank
CXXFLAGS  = ":v"               # :d, :O0 :O3 :w = -Wall
LDFLAGS   = ":mvm"
LIBS      = ":f :s"

load "~/code/build/app2.rake"

# task :default => [:test]
