# -*- ruby -*-

SRCS      = %w{ unordered_map.cpp }
TEST_SRCS = %w{ test_unordered_map.cpp }
APP       = "unordered_map"
CXX       = "xcrun"
CXXFLAGS  = ":d"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
