task :default => ["hello"]

file "main.o" =>  ["main.c", "greet.h"] do
  sh "gcc -c -o main.o main.c"
end

file "greet.o" => ["greet.c"] do
  sh "gcc -c -o greet.o greet.c"
end

file "hello" => ["main.o", "greet.o"] do
  sh "gcc -o hello main.o greet.o"
end
