# -*- ruby -*-

APP       = "var_int"
APP_TEST  = "test_#{APP}"
SRCS      = %w{ /Users/yielding/code/develop/src/ByteBuffer.cpp
                ./main.cpp 
              }

TEST_SRCS = %w{ /Users/yielding/code/develop/src/ByteBuffer.cpp
                ./test_main.cpp
              }

INCS      = "/Users/yielding/code/develop/include"
CXX       = "xcrun"         # c++0x, clang++, blank
CXXFLAGS  = ":v :O3"          # :d, :O0 :O3 :w = -Wall
LIBS      = ""

load "~/code/build/app2.rake"

task :default => [:test]
