/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define WORLD_STABILITY "___dtrace_stability$world$v1$5_5_5_1_1_5_1_1_5_5_5_5_5_5_5"

#define WORLD_TYPEDEFS "___dtrace_typedefs$world$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	WORLD_LOOP(arg0) \
do { \
	__asm__ volatile(".reference " WORLD_TYPEDEFS); \
	__dtrace_probe$world$loop$v1$696e74(arg0); \
	__asm__ volatile(".reference " WORLD_STABILITY); \
} while (0)
#define	WORLD_LOOP_ENABLED() \
	({ int _r = __dtrace_isenabled$world$loop$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$world$loop$v1$696e74(int);
extern int __dtrace_isenabled$world$loop$v1(void);

#else

#define	WORLD_LOOP(arg0) \
do { \
	} while (0)
#define	WORLD_LOOP_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
