# -*- ruby -*-

HOME      = "#{ENV['HOME']}/code/app/usbmux-proxy2/usbmux-proxy2"
DEV       = "#{ENV['HOME']}/code/develop"
APP       = "usbmux"
APP_TEST  = "test_#{APP}"
SRCS      = %W{ #{DEV}/src/ByteBuffer.cpp
                #{DEV}/src/Base64.cpp
                #{DEV}/src/PlistParser.cpp
                #{HOME}/BPlistRepr.cpp
                #{HOME}/BPlist.cpp
                #{HOME}/usbmux2.cpp
                #{HOME}/main.cpp 
              }

TEST_SRCS = %W{ #{DEV}/src/ByteBuffer.cpp
                #{DEV}/src/Base64.cpp
                #{DEV}/src/PlistParser.cpp
                #{HOME}/BPlistRepr.cpp
                #{HOME}/BPlist.cpp
                #{HOME}/usbmux2.cpp
                #{HOME}/test_main.cpp
              }

INCS      = "#{HOME} #{DEV}/include"
CXX       = "xcrun"           # xcrun(clang++ for Apple compiler), c++0x, clang++, blank
#CXX      = "c++11"           # xcrun(clang++ for Apple compiler), c++0x, clang++, blank
CXXFLAGS  = ":v :O3"          # :d, :O0 :O3 :w = -Wall
LIBS      = ":s :f"

load "~/code/build/app2.rake"

# task :default => [:test]
