#-*- ruby -*-   

require 'rake/clean'

TARGET = 'main'

task :default => [TARGET]

CLEAN.include("*.o")
CLOBBER.include(TARGET)

LIBS     = '-pthread -lm -lc -lruby'
CXXFLAGS = '-I/opt/local/lib/ruby/1.8/i686-darwin9'
LDFLAGS  = '-L. -L/usr/lib -L/opt/local/lib'
SRC      = FileList['*.cpp']
OBJ      = SRC.ext('o')

rule '.o' => '.cpp' do |t|
  sh "g++ -O2 -c -o #{t.name} #{t.source} #{CXXFLAGS}"
end

file TARGET => OBJ do
  puts "TARGET -> OBJ"
  sh "g++ -o main #{OBJ} #{LDFLAGS} #{LIBS}"
  sh "strip ./main"
end
                
file "data_model_wrapper.cpp" => "data_model.i" do |t|
  puts "data_model.i"
  sh "swig -ruby -c++ -o #{t.name} data_model.i"
end                                
    
task :run => [TARGET] do
  puts "run => TARGE"
  sh "./#{TARGET}"
end

file 'main.o'       => ['main.cpp', 'data_model_wrapper.cpp']
file 'data_model.o' => ['data_model.cpp']
file 'data_model_wrapper.o' => ['data_model_wrapper.cpp']
