# -*- ruby -*-

SRCS      = %w{ ./fs.basic.cpp}
TEST_SRCS = %w{test_fs.basic.cpp}
APP       = "tut4"
APP_TEST  = "test_tut4"
CXX       = "clang++"
CXXFLAGS  = ":v :d :w"   # :d , :w=-Wall :O0 :O3
LDFLAGS   = ""
LIBS      = ":s :f"

load '~/code/build/app2.rake'
# CLOBBER.include("a.out")
