# -*- ruby -*-

SRCS      = %w{ ./fs.copy_file.cpp }
APP       = "fs.copy_file"
CXX       = "clang++"
CXXFLAGS  = ":v :d :w"   # :d , :w=-Wall :O0 :O3
LDFLAGS   = ""
LIBS      = ":s :f"

load '~/code/build/app2.rake'
# CLOBBER.include("a.out")

task :default => [:osx]
