# -*- ruby -*-

APP       = "chunk.scan"
SRCS      = %W{ ./chunk.scan.cpp }
CXX       = "clang++"
CXXFLAGS  = ":d"
LIBS      = ""

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
