#-*- ruby -*-   

require 'rake/clean'

TARGET = 'main'

task :default => [:run]

CLEAN.include("*.o")
CLOBBER.include(TARGET)

LIBS     = '-lruby -lobjc -ldl -lboost_thread-xgcc40-mt'
CXXFLAGS = '-I/opt/local/lib/ruby/1.8/i686-darwin9'
SRC      = FileList['*.cpp']
OBJ      = SRC.ext('o')

rule '.o' => '.cpp' do |t|
  sh "g++ -O7 -c -o #{t.name} #{t.source} #{CXXFLAGS}"
end

file TARGET => OBJ do
  sh "g++ -o main #{OBJ} #{LIBS}"
end
                
file "data_model_wrapper.h" => "data_model.i" do |t|
  sh "swig -ruby -c++ -o #{t.name} data_model.i"
end                                
    
task :run => [TARGET] do
  sh "./#{TARGET}"
end

file 'main.o' => ['main.cpp', 'data_model_wrapper.h']
