require 'rake/clean'

CLEAN.include("*.o")
CLOBBER.include("hello")

task :default => ["hello"]

SRC = FileList["*.c"]
OBJ = SRC.ext('o')

rule '.o' => '.c' do |t|
  sh "cc -c -o #{t.name} #{t.source}"
end

file "hello" => OBJ do
  sh "cc -o hello #{OBJ}"
end

file 'main.o' => ['main.c', 'greet.h']
file 'greet.o'=> ['greet.c']
