# -*- ruby -*-

SRCS      = %w{ stack.mm }
TEST_SRCS = %w{ test_stack.mm }
APP       = "stack"
APP_TEST  = "test_stack"
CXX       = "xcrun"
CXXFLAGS  = ":v :d :w :arc"   # :d , :w => -Wall :arc => -fobjc-arc
LDFLAGS   = ""
FRAMEWORKS= "Foundation"
LIBS      = ":s :f"

load '~/code/build/app2.rake'

task :default => [:osx]
