#-*- ruby -*-   

APP      = 'if_vim'
SRCS     = %w{if_vim.cpp}
CXX      = "clang++"
INCS     = ":rice"
#WIN_LIBS = "-lmsvcrt-ruby18-static -lrice"
OSX_LIBS = "-lruby.1.9.1 -lrice"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
