#-*- ruby -*-   

APP      = 'if_vim'
SRCS     = %w{if_vim.cpp}
CXX      = "clang++"
INCS     = ":rice"
LDFLAGS  = ":rice"
LIBS     = ":rice"
#WIN_LIBS = "-lmsvcrt-ruby18-static -lrice"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
