# -*- ruby -*-

SRCS     = %w{pipe.cpp}
APP      = "pipe"
CXX      = "c++0x"    # c++0x, clang++, blank
CXXFLAGS = ":v :O0"
LIBS     = ":t :s" 

load '~/code/build/app2.rake'
CLOBBER.include("*.tee").include("a.out").include("hello")
