# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  app.name = 'Hull'
  app.codesign_certificate = 'iPhone Developer: Chang Ha Lee (E7UHUA76KH)'
  app.identifier = 'kr.yielding.ConvexHull'
  app.icons = ['icon57x57.png', 'icon114x114.png']

  app.provisioning_profile = '/Users/yielding/Library/MobileDevice/Provisioning Profiles/4DFEF585-9522-44B4-BEC2-B32A0D082FA0.mobileprovision'
end
