# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  app.name = 'Hull'
  app.codesign_certificate = 'iPhone Developer: Chang Ha Lee (E7UHUA76KH)'
  app.identifier = 'kr.yielding.ConvexHull'
  app.icons = ['icon57x57.png', 'icon114x114.png']

  app.provisioning_profile = '/Users/yielding/Library/MobileDevice/Provisioning Profiles/B798B91B-3239-4E6A-BD2A-7DB015421268.mobileprovision'
end
