# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

Motion::Project::App.setup do |app|
  app.name = 'Hull'
  app.identifier = 'com.hancomgmd.*'
  app.icons = ['icon57x57.png', 'icon114x114.png']
  app.deployment_target = "8.4"

  app.codesign_certificate = 'iPhone Developer: Chang Ha Lee (E7UHUA76KH)'
  app.provisioning_profile = "/Users/yielding/Dropbox/00.iphone.provisions/ConvexHullAppDevelopment.mobileprovision"
end
