# -*- ruby -*-

APP       = "optional"
APP_TEST  = "test_#{APP}"
SRCS      = %W{ ./optional.cpp }
TEST_SRCS = %W{  } + SRCS
CXX       = "xcrun"
CXXFLAGS  = ":Os"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
