# -*- ruby -*-

APP      = "sample1"
SRCS     = %w{ ./sample1.cpp }
CXX      = "xcrun"    # c++0x, clang++, blank
CXXFLAGS = ":v :d :w"         # :d , :w=-Wall :O0 :O3
LIBS     = "gtest"

load '~/code/build/app2.rake'
# CLOBBER.include("a.out")
