# -*- ruby -*-
# 

SRCS     = %w{bounded.buffer.cpp}
APP      = "bounded.buffer"
OSX_LIBS = "-lboost_thread-mt -lboost_system-mt"

DIR = File.dirname __FILE__

load '~/code/build/app.rake'

task :default => [:osx]
