# -*- ruby -*-

SRC       = "max"
SRCS      = %W{ #{SRC}.cpp }
TEST_SRCS = %W{ test_#{SRC}.cpp }
APP       = "#{SRC}"
CXX       = "g++"
#CXXFLAGS  = ":d"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
