# -*- ruby -*-

APP       = "main"
SRCS      = %W{ ./main.cpp }
CXX       = "g++"
CXXFLAGS  = ":Os"
LIBS      = ""

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
