/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define PRIMES_STABILITY "___dtrace_stability$primes$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define PRIMES_TYPEDEFS "___dtrace_typedefs$primes$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	PRIMES_PRIMECALC_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " PRIMES_TYPEDEFS); \
	__dtrace_probe$primes$primecalc__done$v1$6c6f6e67$696e74(arg0, arg1); \
	__asm__ volatile(".reference " PRIMES_STABILITY); \
} while (0)
#define	PRIMES_PRIMECALC_DONE_ENABLED() \
	({ int _r = __dtrace_isenabled$primes$primecalc__done$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	PRIMES_PRIMECALC_START(arg0) \
do { \
	__asm__ volatile(".reference " PRIMES_TYPEDEFS); \
	__dtrace_probe$primes$primecalc__start$v1$6c6f6e67(arg0); \
	__asm__ volatile(".reference " PRIMES_STABILITY); \
} while (0)
#define	PRIMES_PRIMECALC_START_ENABLED() \
	({ int _r = __dtrace_isenabled$primes$primecalc__start$v1(); \
		__asm__ volatile(""); \
		_r; })
#define	PRIMES_PRIMECALC_TABLESIZE(arg0) \
do { \
	__asm__ volatile(".reference " PRIMES_TYPEDEFS); \
	__dtrace_probe$primes$primecalc__tablesize$v1$6c6f6e67(arg0); \
	__asm__ volatile(".reference " PRIMES_STABILITY); \
} while (0)
#define	PRIMES_PRIMECALC_TABLESIZE_ENABLED() \
	({ int _r = __dtrace_isenabled$primes$primecalc__tablesize$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$primes$primecalc__done$v1$6c6f6e67$696e74(long, int);
extern int __dtrace_isenabled$primes$primecalc__done$v1(void);
extern void __dtrace_probe$primes$primecalc__start$v1$6c6f6e67(long);
extern int __dtrace_isenabled$primes$primecalc__start$v1(void);
extern void __dtrace_probe$primes$primecalc__tablesize$v1$6c6f6e67(long);
extern int __dtrace_isenabled$primes$primecalc__tablesize$v1(void);

#else

#define	PRIMES_PRIMECALC_DONE(arg0, arg1) \
do { \
	} while (0)
#define	PRIMES_PRIMECALC_DONE_ENABLED() (0)
#define	PRIMES_PRIMECALC_START(arg0) \
do { \
	} while (0)
#define	PRIMES_PRIMECALC_START_ENABLED() (0)
#define	PRIMES_PRIMECALC_TABLESIZE(arg0) \
do { \
	} while (0)
#define	PRIMES_PRIMECALC_TABLESIZE_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
