# -*- ruby -*-

APP       = "serv_cli"
SRCS      = %W{ serv_cli.cpp }
CXX       = "g++"
CXXFLAGS  = ":Os"
LIBS      = "zmq"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
