# -*- ruby -*-

APP       = "hfsplus"
APP_TEST  = "test_#{APP}"
SRCS      = %w{ 
                ./attribute_btree.cpp
                ./catalog_btree.cpp
                ./develop/src/ByteBuffer.cpp
                ./develop/src/HexUtil.cpp
                ./develop/src/PTreeParser.cpp
                ./emf_file.cpp
                ./emf_volume.cpp
                ./extents_btree.cpp
                ./hfs_file.cpp
                ./hfs_header.cpp
                ./hfs_key.cpp
                ./hfs_volume.cpp
                ./journal.cpp
                ./key_bag.cpp
                ./main.cpp 
                ./signature.cpp
                ./unicode_compare.cpp
              }

TEST_SRCS = %w{ 
                ./hfs_key.cpp
                ./develop/src/ByteBuffer.cpp
                ./develop/src/PTreeParser.cpp
                ./develop/src/Base64.cpp
                ./key_bag.cpp ./test_key_bag.cpp
              }
INCS      = "./develop/include"
CXX       = "c++11"          # c++0x, clang++, blank
CXXFLAGS  = ":v :d"          # :d, :O0 :O3 :w = -Wall
LIBS      = ":r :t :s :f ssl crypto"

load "~/code/build/app2.rake"

# task :default => [:test]
