# -*- ruby -*-
APP       = "jukebox"
SRCS      = %w{ ./jukebox.cpp }

INCS      = ":mvm"
CXX       = "xcrun"            # c++0x, clang++, blank
CXXFLAGS  = ":v :O3"           # :d, :O0 :O3 :w = -Wall
LDFLAGS   = ":mvm"
LIBS      = "mruby"

load "~/code/build/app2.rake"

task :default => [:osx]
