# -*- ruby -*-

APP       = "jukebox"
APP_TEST  = "test_#{APP}"
SRCS      = %w{ ./jukebox.cpp }

TEST_SRCS = %w{ } 

INCS      = ":mvm"
CXX       = "xcrun"            # c++0x, clang++, blank
CXXFLAGS  = ":v :O3"           # :d, :O0 :O3 :w = -Wall
LDFLAGS   = ":mvm"

load "~/code/build/app2.rake"

task :default => [:osx]
