# -*- ruby -*-

SRCS     = %w{pipe.out.cpp}
APP      = "pipe.out"
CXX      = "clang++"    # c++0x, clang++, blank
CXXFLAGS = ":v :Os"
LIBS     = ":t :s" 

load '~/code/build/app2.rake'
CLOBBER.include("*.tee").include("a.out").include("hello")
task :default => [:osx]
