# -*- ruby -*-

SRCS      = %w{ ./addressof.cpp }
TEST_SRCS = %w{ ./test_addressof.cpp }
APP       = "addressof"
CXX       = "xcrun"
CXXFLAGS  = ":Os"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'

task :default => [:osx]
