# -*- ruby -*-

APP      = "binary"
SRCS     = %w{ ./file.binary.cpp }
CXX      = "c++11"
CXXFLAGS = ":v"

DIR = File.dirname __FILE__

load '~/code/build/app2.rake'
CLOBBER.add(["a.out", "log.bin"])
