# -*- ruby -*-

SRCS      = %w{ ./print_time.cpp }
TEST_SRCS = %w{ ./print_time.cpp }
APP       = "print_time"
APP_TEST  = "test_print_time"
CXX       = "c++11"
CXXFLAGS  = ":v :d :w"   # :d , :w=-Wall :O0 :O3
LDFLAGS   = ""
LIBS      = ":s :f boost_chrono-mt"

load '~/code/build/app2.rake'
# CLOBBER.include("a.out")
